### ISSUE TITLE
Singularity-python container not working

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/singularity-python#86]
Hi,

maybe I'm doing something wrong ... but I'm not being able to use the containerized `singularity-python`. I'm using the recipe (Singularity.container) provided in this repository. It builds without problems but when I try to run `sregistry` it crashes. 

This is the error message:
```
$ ./sregistry.simg push --name mso4sc/sregistry --tag 2.4.1 sregitry.simg 
Traceback (most recent call last):
  File "/opt/conda/bin/sregistry", line 11, in <module>
    load_entry_point('singularity==2.4.1', 'console_scripts', 'sregistry')()
  File "/opt/conda/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/registry/main/__init__.py", line 208, in main
    subparser=subparsers[args.command])
  File "/opt/conda/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/registry/main/push.py", line 47, in main
    compress=args.compress)
  File "/opt/conda/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/registry/client/push.py", line 65, in push
    metadata = cli.inspect(image_path=path, quiet=True)
  File "/opt/conda/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/cli/__init__.py", line 271, in inspect
    output = self.run_command(cmd)
  File "/opt/conda/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/cli/__init__.py", line 55, in run_command
    result = run_command(cmd,sudo=sudo)
  File "/opt/conda/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/utils.py", line 89, in run_command
    output = Popen(cmd,stderr=STDOUT,stdout=PIPE)
  File "/opt/conda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'singularity'
```

Maybe is this related with paths or environment variables? Any idea?

Thanks in advance!

**Comment by vsoch** [comment]
Do you have singularity installed?

**Comment by vsoch** [comment]
And I'm not going to be developing the registry client here moving forward - the work is moving to singularity global client --> https://github.com/singularityhub/sregistry-cli If you take a look at the add/globus branch there is a huge amount of work in progress! But even the minimal start on the main branch might be enough for your basic use of a registry at this point. Give it a try?

**Comment by victorsndvg** [comment]
Yes, singularity is installed. It works perfectly in a docker container, but after bootstraping a Singularity image from the docker image it fails. Any idea?

I already check `sregistry-cli` but I don't feel very confident providing a pre-release version to users.
If you think the current status of `sregistry-cli` can be used in production, then I will use it.

Let me know

**Comment by vsoch** [comment]
hey @victorsndvg ! I've been working on it night and day, it's coming along nicely and likely will be ready early January after the new year.

The error is telling you the subprocess command cannot find a "singularity" executable, so I would test out issuing a command to the image to test if singularity is installed, something like `which singularity`. Likely you were using the installation on the host (it's not in the container) and you have done something so the host isn't being seen.

**Comment by victorsndvg** [comment]
Yeah @vsoch , I follow you and I know you are a hard-worker building amazing tools :smile: . I really appreciate your work. 

Ok, to have it ready for January is great! Meanwhile I can use Singularity-python-sregistry and test sregistry-cli.

Now that I understood the problem, I'm going to try to discover what is happening and I will report it again. Thanks!
